name: Security
description: 'Hardening an application: encryption, request protection and vulnerability
  scanning'
projects:
- achyutn/laravel-hls
- akaunting/laravel-firewall
- albertcht/invisible-recaptcha
- andreapollastri/checkpoint
- anhskohbo/no-captcha
- bepsvpt/secure-headers
- cjmellor/browser-sessions
- derekcodes/turnstile-laravel
- dgtlss/warden
- ercsctt/laravel-file-encryption
- fuko-php/masked
- grazulex/laravel-sharelink
- hashids/hashids
- hdaklue/larapath
- intermax/veil
- jenssegers/optimus
- laravel-chronicle/core
- mokhosh/muddle
- nicobleiler/php-passphrase
- oneduo/laravel-recaptcha-enterprise
- pragmarx/firewall
- promptphp/intercept
- rahul900day/laravel-captcha
- rahulalam31/laravel-abuse-ip
- roave/security-advisories
- ryangjchandler/laravel-cloudflare-turnstile
- salehhashemi/laravel-otp-manager
- sensiolabs/security-advisories
- spatie/laravel-ciphersweet
- spatie/laravel-csp
- spatie/laravel-honeypot
- spatie/laravel-littlegatekeeper
- sunspikes/clamav-validator
- yorcreative/laravel-scrubber
