name: Deployment
description: Deploying releases and running deploy-time tasks
projects:
- ajaxray/laravel-server-sync
- deployer/deployer
- dragon-code/laravel-actions
- dragon-code/laravel-deploy-operations
- dusterio/laravel-aws-worker
- hammerstone/airdrop
- justpark/envoyer-deploy
- juststeveking/laravel-envoyer-sdk
- laravel/envoy
- laravel/vapor-cli
- laravel/vapor-core
- laravel/vapor-ui
- lorisleiva/laravel-deployer
- pragmarx/version
- salahhusa9/laravel-updater
- sammyjo20/lasso
- timokoerber/laravel-one-time-operations
- wilbergroup/airdrop
